/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormularzRouteImport } from './routes/formularz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUstawieniaRouteImport } from './routes/_authenticated/ustawienia'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedMagazynRouteImport } from './routes/_authenticated/magazyn'
import { Route as AuthenticatedKonsolidacjaRouteImport } from './routes/_authenticated/konsolidacja'
import { Route as AuthenticatedKalendarzRouteImport } from './routes/_authenticated/kalendarz'
import { Route as AuthenticatedHistoriaRouteImport } from './routes/_authenticated/historia'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedBotRouteImport } from './routes/_authenticated/bot'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksTransportRemindersRouteImport } from './routes/api/public/hooks/transport-reminders'
import { Route as ApiPublicHooksFetchFuelPriceRouteImport } from './routes/api/public/hooks/fetch-fuel-price'

const FormularzRoute = FormularzRouteImport.update({
  id: '/formularz',
  path: '/formularz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUstawieniaRoute = AuthenticatedUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMagazynRoute = AuthenticatedMagazynRouteImport.update({
  id: '/magazyn',
  path: '/magazyn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKonsolidacjaRoute =
  AuthenticatedKonsolidacjaRouteImport.update({
    id: '/konsolidacja',
    path: '/konsolidacja',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalendarzRoute = AuthenticatedKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriaRoute = AuthenticatedHistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotRoute = AuthenticatedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTransportRemindersRoute =
  ApiPublicHooksTransportRemindersRouteImport.update({
    id: '/api/public/hooks/transport-reminders',
    path: '/api/public/hooks/transport-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFetchFuelPriceRoute =
  ApiPublicHooksFetchFuelPriceRouteImport.update({
    id: '/api/public/hooks/fetch-fuel-price',
    path: '/api/public/hooks/fetch-fuel-price',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formularz': typeof FormularzRoute
  '/bot': typeof AuthenticatedBotRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historia': typeof AuthenticatedHistoriaRoute
  '/kalendarz': typeof AuthenticatedKalendarzRoute
  '/konsolidacja': typeof AuthenticatedKonsolidacjaRoute
  '/magazyn': typeof AuthenticatedMagazynRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/fetch-fuel-price': typeof ApiPublicHooksFetchFuelPriceRoute
  '/api/public/hooks/transport-reminders': typeof ApiPublicHooksTransportRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formularz': typeof FormularzRoute
  '/bot': typeof AuthenticatedBotRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historia': typeof AuthenticatedHistoriaRoute
  '/kalendarz': typeof AuthenticatedKalendarzRoute
  '/konsolidacja': typeof AuthenticatedKonsolidacjaRoute
  '/magazyn': typeof AuthenticatedMagazynRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/fetch-fuel-price': typeof ApiPublicHooksFetchFuelPriceRoute
  '/api/public/hooks/transport-reminders': typeof ApiPublicHooksTransportRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/formularz': typeof FormularzRoute
  '/_authenticated/bot': typeof AuthenticatedBotRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historia': typeof AuthenticatedHistoriaRoute
  '/_authenticated/kalendarz': typeof AuthenticatedKalendarzRoute
  '/_authenticated/konsolidacja': typeof AuthenticatedKonsolidacjaRoute
  '/_authenticated/magazyn': typeof AuthenticatedMagazynRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/_authenticated/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/fetch-fuel-price': typeof ApiPublicHooksFetchFuelPriceRoute
  '/api/public/hooks/transport-reminders': typeof ApiPublicHooksTransportRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formularz'
    | '/bot'
    | '/crm'
    | '/dashboard'
    | '/historia'
    | '/kalendarz'
    | '/konsolidacja'
    | '/magazyn'
    | '/transport'
    | '/ustawienia'
    | '/api/public/leads'
    | '/api/public/hooks/fetch-fuel-price'
    | '/api/public/hooks/transport-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/formularz'
    | '/bot'
    | '/crm'
    | '/dashboard'
    | '/historia'
    | '/kalendarz'
    | '/konsolidacja'
    | '/magazyn'
    | '/transport'
    | '/ustawienia'
    | '/api/public/leads'
    | '/api/public/hooks/fetch-fuel-price'
    | '/api/public/hooks/transport-reminders'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/formularz'
    | '/_authenticated/bot'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/historia'
    | '/_authenticated/kalendarz'
    | '/_authenticated/konsolidacja'
    | '/_authenticated/magazyn'
    | '/_authenticated/transport'
    | '/_authenticated/ustawienia'
    | '/api/public/leads'
    | '/api/public/hooks/fetch-fuel-price'
    | '/api/public/hooks/transport-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormularzRoute: typeof FormularzRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicHooksFetchFuelPriceRoute: typeof ApiPublicHooksFetchFuelPriceRoute
  ApiPublicHooksTransportRemindersRoute: typeof ApiPublicHooksTransportRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formularz': {
      id: '/formularz'
      path: '/formularz'
      fullPath: '/formularz'
      preLoaderRoute: typeof FormularzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ustawienia': {
      id: '/_authenticated/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof AuthenticatedUstawieniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magazyn': {
      id: '/_authenticated/magazyn'
      path: '/magazyn'
      fullPath: '/magazyn'
      preLoaderRoute: typeof AuthenticatedMagazynRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konsolidacja': {
      id: '/_authenticated/konsolidacja'
      path: '/konsolidacja'
      fullPath: '/konsolidacja'
      preLoaderRoute: typeof AuthenticatedKonsolidacjaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendarz': {
      id: '/_authenticated/kalendarz'
      path: '/kalendarz'
      fullPath: '/kalendarz'
      preLoaderRoute: typeof AuthenticatedKalendarzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historia': {
      id: '/_authenticated/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof AuthenticatedHistoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot': {
      id: '/_authenticated/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthenticatedBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/transport-reminders': {
      id: '/api/public/hooks/transport-reminders'
      path: '/api/public/hooks/transport-reminders'
      fullPath: '/api/public/hooks/transport-reminders'
      preLoaderRoute: typeof ApiPublicHooksTransportRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fetch-fuel-price': {
      id: '/api/public/hooks/fetch-fuel-price'
      path: '/api/public/hooks/fetch-fuel-price'
      fullPath: '/api/public/hooks/fetch-fuel-price'
      preLoaderRoute: typeof ApiPublicHooksFetchFuelPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBotRoute: typeof AuthenticatedBotRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoriaRoute: typeof AuthenticatedHistoriaRoute
  AuthenticatedKalendarzRoute: typeof AuthenticatedKalendarzRoute
  AuthenticatedKonsolidacjaRoute: typeof AuthenticatedKonsolidacjaRoute
  AuthenticatedMagazynRoute: typeof AuthenticatedMagazynRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedUstawieniaRoute: typeof AuthenticatedUstawieniaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBotRoute: AuthenticatedBotRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoriaRoute: AuthenticatedHistoriaRoute,
  AuthenticatedKalendarzRoute: AuthenticatedKalendarzRoute,
  AuthenticatedKonsolidacjaRoute: AuthenticatedKonsolidacjaRoute,
  AuthenticatedMagazynRoute: AuthenticatedMagazynRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedUstawieniaRoute: AuthenticatedUstawieniaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FormularzRoute: FormularzRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicHooksFetchFuelPriceRoute: ApiPublicHooksFetchFuelPriceRoute,
  ApiPublicHooksTransportRemindersRoute: ApiPublicHooksTransportRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
